import type { Product } from './supabase/database.types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'mock-0',
    ordre: 0,
    nom: 'Rose Gold · Black',
    ref: 'PC-RG-BLK-01',
    collection: 'Polycarbon',
    prix: 2990,
    reduction: null,
    prix_reduc: null,
    mention: 'Populaire',
    stock: 10,
    boitier: 'Polycarbonate',
    materiau: null,
    bracelet: 'Caoutchouc',
    fermoir: null,
    lunette: 'Rose Gold brossé',
    fond: null,
    cadran: 'Noir mat',
    aiguilles: null,
    verre: null,
    mouvement: null,
    resistance: '3 ATM',
    sku: null,
    description:
      "La montre emblématique de D1 Milano. Boîtier octogonal en polycarbonate avec lunette Rose Gold brossée, cadran noir mat. Bracelet caoutchouc. Le parfait équilibre entre sophistication et modernité.",
    photo_principale: null,
    photo_2: null,
    photo_3: null,
    photo_4: null,
    photo_5: null,
    actif: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-1',
    ordre: 1,
    nom: 'All Black',
    ref: 'PC-AB-01',
    collection: 'Polycarbon',
    prix: 2790,
    reduction: null,
    prix_reduc: null,
    mention: 'Nouveau',
    stock: 8,
    boitier: 'Polycarbonate',
    materiau: null,
    bracelet: 'Caoutchouc',
    fermoir: null,
    lunette: 'Black mat',
    fond: null,
    cadran: 'Noir',
    aiguilles: null,
    verre: null,
    mouvement: null,
    resistance: '3 ATM',
    sku: null,
    description:
      "Version All Black absolue. Le monochrome poussé à l'extrême. Boîtier, lunette et bracelet entièrement noirs, pour une silhouette radicale et intemporelle.",
    photo_principale: null,
    photo_2: null,
    photo_3: null,
    photo_4: null,
    photo_5: null,
    actif: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    ordre: 2,
    nom: 'Silver · Navy Blue',
    ref: 'UT-SV-NB-01',
    collection: 'Ultra Thin',
    prix: 3290,
    reduction: null,
    prix_reduc: null,
    mention: null,
    stock: 5,
    boitier: 'Acier brossé',
    materiau: null,
    bracelet: 'Cuir',
    fermoir: null,
    lunette: null,
    fond: null,
    cadran: 'Bleu nuit',
    aiguilles: null,
    verre: null,
    mouvement: null,
    resistance: '3 ATM',
    sku: null,
    description:
      "La finesse à l'état pur. Boîtier octogonal ultra-plat en acier brossé, cadran bleu nuit profond. Pour l'homme qui ne fait jamais de concession sur l'élégance.",
    photo_principale: null,
    photo_2: null,
    photo_3: null,
    photo_4: null,
    photo_5: null,
    actif: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    ordre: 3,
    nom: 'Silver Skeleton',
    ref: 'SK-SV-01',
    collection: 'Skeleton',
    prix: 4490,
    reduction: null,
    prix_reduc: null,
    mention: 'Premium',
    stock: 3,
    boitier: 'Polycarbonate blanc',
    materiau: null,
    bracelet: 'Caoutchouc',
    fermoir: null,
    lunette: null,
    fond: null,
    cadran: null,
    aiguilles: null,
    verre: null,
    mouvement: 'Squelette automatique',
    resistance: '3 ATM',
    sku: null,
    description:
      "Le temps visible. Mécanisme squelette apparent sous un boîtier octogonal. Une pièce pour les amateurs qui veulent voir l'âme de leur montre.",
    photo_principale: null,
    photo_2: null,
    photo_3: null,
    photo_4: null,
    photo_5: null,
    actif: true,
    created_at: new Date().toISOString(),
  },
]

/** Map collection name → filter key used in catalogue */
export const COLLECTION_FILTER: Record<string, string> = {
  Polycarbon: 'polycarbon',
  'Ultra Thin': 'ultrathin',
  Skeleton: 'skeleton',
  Tahoe: 'tahoe',
}

/** Format price from number to MAD string */
export function formatPrice(price: number): string {
  return price.toLocaleString('fr-MA') + ' MAD'
}
